
export const SYSTEM_ATTRIBUTES = [
  {
    key: "lastSubbedAt",
    label: "Last Time User Subbed",
    type: "date",
    options: [],
    userEditable: false,
    defaultValue: null,
    description: "Most recent date the user was assigned and completed a sub job.",
    source: "system",
    readOnly: true,
  },
  {
    key: "assignedJobCount",
    label: "Total Assigned Jobs",
    type: "number",
    options: [],
    userEditable: false,
    defaultValue: null,
    description: "Total number of jobs this user has been assigned.",
    source: "system",
    readOnly: true,
  },
  {
    key: "hasSubbedInLast7Days",
    label: "Has Subbed in Last 7 Days",
    type: "boolean",
    description: "True if the user has subbed at least once in the last 7 days.",
    options: [],
    userEditable: false,
    defaultValue: null,
    source: "system",
    readOnly: true,
  },
  {
    key: "totalMeetingsHosted",
    label: "Total Meetings Hosted",
    type: "number",
    options: [],
    userEditable: false,
    defaultValue: 0,
    description: "Total number of meetings this user has hosted or co-hosted.",
    source: "system",
    readOnly: true,
  },
];