name: Deploy Frontend to GitHub Pages

on:
  # push:
  #   branches:
  #     - main   # or whichever branch you develop on
  workflow_dispatch:   # allows manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # required to push to gh-pages

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22   # or match your local version
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./client   # adjust if frontend lives in /client
        run: npm ci

      - name: Build project
        working-directory: ./client
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/build
          publish_branch: gh-pages
